describe('Dropdown Menu and Refresh Button Testing', () => {
    beforeEach('Bypass login page', () => {
        cy.visit('/')
        cy.get('input').eq(0).type('username@email.com')
        cy.get('input').eq(1).type('password')
        cy.get('button').eq(0).click()
    })
    it('Clicking on each Dropdown Menu option works without error', () => {
        cy.get('#Dropdown').click()
        cy.get('#15_Minutes').click()
        cy.get('#Dropdown').click()
        cy.get('#30_Minutes').click()
        cy.get('#Dropdown').click()
        cy.get('#1_Hour').click()
        cy.get('#Dropdown').click()
        cy.get('#4_Hours').click()
        cy.get('#Dropdown').click()
        cy.get('#12_Hours').click()
        cy.get('#Dropdown').click()
        cy.get('#1_Day').click()
    })
    it('Clicking on Refresh Button works without error', () => {
        cy.get('.MuiIconButton-root').click()
    })
})