INSERT INTO LOG_DETAILS_T VALUES
    ('crm_server_000001', 
        'CRM', 
        'Customer', 
        '1.0', 
        'CRM-Customer-CRM_Adapter-Publish_Customer_Update-1212', 
        'eai_crm_server_111111', 
        'EAI_DOMAIN_1', 
        'crm_server', 
        'CRM_Adapter', 
        'Publish_Customer_Update', 
        'Publish_Customer_Update', 
        '10', 
        '71', 
        '2020-12-12 01:24:23', 
        'INTERNAL',
        '1212',
        'ReportSituation',
        'Customer Update Started',
        'Received a customer update start event'
    );